DZ4/ChessGameManager/ChessGameManager/Controllers/ChessGameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.IO;
using System.Web.UI;

namespace ChessGameManager.Controllers
{
    public class ChessGameController : Controller
    {
        ~ChessGameController()
        {
            if (db!=null)
            {
                db.Dispose();
            }
        }
        private readonly ModelContainer db = new ModelContainer();
        HttpCookie cookie = new HttpCookie("Warning");
        // GET: ChessGame
        public ActionResult Index()
        {
            if (db.People.Count() < 2)
            {
                Response.Write("<script>alert('You need to add atleast 2 players to create a game')</script>");
            }
            return View(db.ChessGames);
        }

        // GET: ChessGame/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChessGame chessGame = db.ChessGames
                .Include(cg => cg.UploadedFiles)
                .SingleOrDefault(cg => cg.IDChessGame == id);
            if (chessGame == null)
            {
                return HttpNotFound();
            }
            return View(chessGame);
        }

        // GET: ChessGame/Create
        public ActionResult Create()
        {
            var people = db.People;
            ViewBag.People = db.People;       
            if (people.Count() < 2)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        // POST: ChessGame/Create
        [HttpPost]
        public ActionResult Create(ChessGame chessGame,
            int firstPlayerID,
            int secondPlayerID,
            IEnumerable<HttpPostedFileBase> files)
        {
            chessGame.FirstPlayer = db.People.Find(firstPlayerID);
            chessGame.SecondPlayer = db.People.Find(secondPlayerID);
            if (ModelState.IsValid)
            {
                chessGame.UploadedFiles = new List<UploadedFile>();
                foreach (var file in files)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        var picture = new UploadedFile
                        {
                            Name = Path.GetFileName(file.FileName),
                            ContentType = file.ContentType
                        };
                        using (var reader = new BinaryReader(file.InputStream))
                        {
                            picture.Content = reader.ReadBytes(file.ContentLength);
                        }
                        chessGame.UploadedFiles.Add(picture);
                    }
                }

                db.ChessGames.Add(chessGame);
                db.SaveChanges();

            }
            return RedirectToAction("Index");  
        }

        // GET: ChessGame/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            ChessGame chessGame = db.ChessGames
                .Include(cg => cg.UploadedFiles)
                .SingleOrDefault(cg => cg.IDChessGame == id);
            if (chessGame == null)
            {
                return HttpNotFound();
            }
            IEnumerable<Person> people = db.People.Where(p => p.IDPerson != chessGame.FirstPlayer.IDPerson);
            people = people.Prepend(chessGame.FirstPlayer);

            ViewBag.People1 = people;

            people = people.Where(p => p.IDPerson != chessGame.SecondPlayer.IDPerson);
            people = people.Prepend(chessGame.SecondPlayer).ToList();

            ViewBag.People2 = people;


            return View(chessGame);
        }

        // POST: ChessGame/Edit/5
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditConfirmed(int id,
            int firstPlayerID,
            int secondPlayerID,
            IEnumerable<HttpPostedFileBase> files)
        {
            ChessGame chessGameToUpdate = db.ChessGames.Find(id);
            if (TryUpdateModel(chessGameToUpdate, "",
                new string[] { "Location, FirstPlayer, SecondPlayer"}))
            {
                chessGameToUpdate.FirstPlayer = db.People.Find(firstPlayerID);
                chessGameToUpdate.SecondPlayer = db.People.Find(secondPlayerID);

                if (chessGameToUpdate.UploadedFiles == null)
                {
                    chessGameToUpdate.UploadedFiles = new List<UploadedFile>(); 
                }
                foreach (var file in files)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        var picture = new UploadedFile
                        {
                            Name = Path.GetFileName(file.FileName),
                            ContentType = file.ContentType
                        };
                        using (var reader = new BinaryReader(file.InputStream))
                        {
                            picture.Content = reader.ReadBytes(file.ContentLength);
                        }
                        chessGameToUpdate.UploadedFiles.Add(picture);
                    }
                }

                db.Entry(chessGameToUpdate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(chessGameToUpdate);
        }

        // GET: ChessGame/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChessGame chessGame = db.ChessGames
                .Include(cg => cg.UploadedFiles)
                .SingleOrDefault(cg => cg.IDChessGame == id);
            if (chessGame == null)
            {
                return HttpNotFound();
            }
            return View(chessGame);
        }

        // POST: ChessGame/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            db.UploadedFiles.RemoveRange(db.UploadedFiles.Where(file => file.ChessGameIDChessGame == id));
            db.ChessGames.Remove(db.ChessGames.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DZ4/ChessGameManager/ChessGameManager/Controllers/FileController.cs
using System.Web.Mvc;

namespace ChessGameManager.Controllers
{
    public class FileController : Controller
    {
        ~FileController()
        {
            if (db != null)
            {
                db.Dispose();
            }
        }
        private readonly ModelContainer db = new ModelContainer();
        // GET: File
        public ActionResult Index(int id)
        {
            var uploadedFile = db.UploadedFiles.Find(id);
            return File(uploadedFile.Content, uploadedFile.ContentType);
        }

        public ActionResult Delete(int id)
        {
            db.UploadedFiles.Remove(db.UploadedFiles.Find(id));
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.AbsolutePath);
        }

    }
}

DZ4/ChessGameManager/ChessGameManager/Views/ChessGame/Create.cshtml
@model ChessGameManager.ChessGame

@{
    ViewBag.Title = "Create";
    var people = (ViewBag.People as IEnumerable<Person>).ToList();
    var ddlOpcije = new SelectList(people, dataValueField:"IDPerson", dataTextField:$"FirstName");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "ChessGame", null, FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ChessGame</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstPlayer, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("firstPlayerID", ddlOpcije, htmlAttributes: new { @class = "ddl form-control" })
            
            @Html.ValidationMessageFor(model => model.FirstPlayer, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SecondPlayer, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("secondPlayerID", ddlOpcije, htmlAttributes: new { @class = "ddl form-control" })

            @Html.ValidationMessageFor(model => model.SecondPlayer, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Picture", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="Picture" multiple accept="image/*" name="files" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input  type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    <button class="btn btn-warning">@Html.ActionLink("Back to List", "Index")</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DZ4/ChessGameManager/ChessGameManager/Views/ChessGame/Delete.cshtml
@model ChessGameManager.ChessGame

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ChessGame</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDChessGame)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDChessGame)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        @foreach (var uploadedFile in Model.UploadedFiles)
        {
            <dt>
                @uploadedFile.Name
            </dt>

            <dd style="margin-top:10px">
                <img src="~/File?id=@uploadedFile.IDUploadedFille" alt="picture" width="300" height="200" />
            </dd>
        }

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <button class="btn btn-warning">@Html.ActionLink("Back to List", "Index")</button>
        </div>
    }
</div>

DZ4/ChessGameManager/ChessGameManager/Views/ChessGame/Details.cshtml
@model ChessGameManager.ChessGame

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ChessGame</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDChessGame)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDChessGame)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstPlayer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstPlayer.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondPlayer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondPlayer.LastName)
        </dd>

        @foreach (var uploadedFile in Model.UploadedFiles)
        {
            <dt>
                @uploadedFile.Name
            </dt>

            <dd style="margin-top:10px">
                <img src="~/File?id=@uploadedFile.IDUploadedFille" alt="picture" width="300" height="200" />
            </dd>
        }

    </dl>
</div>
<p>
    <button class="btn btn-success">@Html.ActionLink("Edit", "Edit", new { id = Model.IDChessGame })</button>
    <button class="btn btn-warning">@Html.ActionLink("Back to List", "Index")</button>
</p>

DZ4/ChessGameManager/ChessGameManager/Views/ChessGame/Edit.cshtml
@model ChessGameManager.ChessGame

@{
    ViewBag.Title = "Edit";
    var people1 = (ViewBag.People1 as IEnumerable<Person>).ToList();
    var people2 = (ViewBag.People2 as IEnumerable<Person>).ToList();
    var ddlOpcije1 = new SelectList(people1, dataValueField: "IDPerson", dataTextField: "FirstName");
    var ddlOpcije2 = new SelectList(people2, dataValueField: "IDPerson", dataTextField: "FirstName");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "ChessGame", null, FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ChessGame</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.IDChessGame, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IDChessGame, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstPlayer, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("firstPlayerID", ddlOpcije1, htmlAttributes: new { @class = "ddl form-control" })

            @Html.ValidationMessageFor(model => model.FirstPlayer, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SecondPlayer, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("secondPlayerID", ddlOpcije2, htmlAttributes: new { @class = "ddl form-control" })

            @Html.ValidationMessageFor(model => model.SecondPlayer, "", new { @class = "text-danger" })
        </div>
    </div>

    @foreach (var uploadedFile in Model.UploadedFiles)
    {
        <div class="form-group">
            <span class="control-label col-md-2">
                <strong>@uploadedFile.Name</strong><br />
                @Ajax.ActionLink("Delete", "Delete", "File", new { id = uploadedFile.IDUploadedFille },
               new AjaxOptions { HttpMethod = "Post" })
            </span>
            <div class="col-md-10">
                <img src="~/File?id=@uploadedFile.IDUploadedFille" alt="picture" width="300" height="200" />
            </div>
        </div>
    }

    <div class="form-group">
        @Html.Label("Picture", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="Picture" multiple accept="image/*" name="files" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    <button class="btn btn-warning">
        @Html.ActionLink("Back to List", "Index")
    </button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DZ4/ChessGameManager/ChessGameManager/Views/ChessGame/Index.cshtml
@model IEnumerable<ChessGameManager.ChessGame>

@{
    ViewBag.Title = "Chess games";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 ><strong>Chess games</strong></h2>

<button class="btn btn-success" style="margin-bottom:20px">
    <strong>@Html.ActionLink("Create Game", "Create")</strong>
</button>
<button class="btn btn-warning" style="margin-bottom:20px">
    <strong>@Html.ActionLink("Players", "../Person/Index")</strong>
</button>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDChessGame)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstPlayer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SecondPlayer)
        </th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.IDChessGame)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Location)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FirstPlayer.FirstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SecondPlayer.FirstName)
    </td>
    <td>
        <button class="btn btn-success">@Html.ActionLink("Edit", "Edit", new { id = item.IDChessGame })</button>
        <button class="btn btn-info">@Html.ActionLink("Details", "Details", new { id = item.IDChessGame })</button>
        <button class="btn btn-danger">@Html.ActionLink("Delete", "Delete", new { id = item.IDChessGame }) </button>
    </td>
</tr>
}
</table>